apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: workticket
  source:
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.15.0
    chart: keda
    helm:
      values: |
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1001
          fsGroup: 1001
        serviceMonitor:
          enabled: true
          interval: 30s
        prometheus:
          metricServer:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-scaled-objects
  namespace: argocd
spec:
  project: workticket
  source:
    repoURL: https://github.com/WorkTicket/workticket
    targetRevision: main
    path: ops/k8s/keda
  destination:
    server: https://kubernetes.default.svc
    namespace: workticket
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
